# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: geodenoising

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    defaults:
      run:
        shell: bash -l {0}

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2

    - uses: conda-incubator/setup-miniconda@v2
      with:
        channels: conda-forge
        channel-priority: strict
        mamba-version: "*"
        auto-update-conda: false
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        #mamba install torchdata pytorch torchvision torchaudio pytorch-cuda=11.6 -c pytorch-nightly -c nvidia -y
        python -m pip install --upgrade pip
        python -m pip install .[test]

    - uses: actions/cache@v3
      with:
      path: ~/.cache/pip
      key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.cfg') }}
      restore-keys: |
        ${{ runner.os }}-pip-

    - name: Test package with pytest (including notebooks)
      run: |
        python -m pytest --nbval-lax --current-env
